name: gh-pages-deploy
on: 
  push:
    branches:
     - master
permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: write
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
jobs: 
  build-and-deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: npm install
      - name: Set Creds
        run: git config user.name "Stanko" && git config user.email "stanko@bezak.net"
      - name: Deploy 🚀
        run: npm run deploy
